### ISSUE TITLE
Placing a single dot throws an error

### ISSUE THREAD

**Issue by kgram** [agilgur5/react-signature-canvas#11]
Clicking the canvas without dragging throws an error. I believe this to be caused by [this line](https://github.com/agilgur5/react-signature-canvas/blob/master/src/index.js#L25). The default value for `dotSize` is defined as an arrow-function, using `this` to access `props`. However, the function is defined staticly, which means there is no `this` to speak of. Babel transforms the line to 

```return ((void 0).props.minWidth + (void 0).props.maxWidth) / 2```

The result is `Uncaught TypeError: Cannot read property 'props' of undefined`.

There is a [pull request](https://github.com/agilgur5/react-signature-canvas/pull/8/files) attempting to fix this, but unfortunately it basically just hardcodes the default `dotSize` to `2`.

Perhaps passing the `minWidth` and `maxWidth` to the `dotSize`-function could be a solution?

**Comment by agilgur5** [comment]
Ahh that's what the problem was with that function -- great catch @kgram !!

That change would not be backward compatible (would require a major release as per semver), but I believe that would be most optimal, especially as that would make it easier for anyone passing in a `dotSize` function as a prop to just use arguments.

**Comment by Indigo744** [comment]
Any update on this ?

**Comment by indiejoseph** [comment]
+1

**Comment by agilgur5** [comment]
closing, see #8
