### ISSUE TITLE
First time drawing a signature disappears

### ISSUE THREAD

**Issue by khrizt** [agilgur5/react-signature-canvas#13]
Hi,

I'm using this component for some time but I realized that the first time I sign into the component, the drawing disappears while the second time it does not.

This is the code I use to include the component:

```javascript
<SignatureCanvas
  penColor="black"
  canvasProps={{
    height: canvasHeight,
    width: canvasWidth,
  }}
  ref={(elem) => {
    this.signatureCanvas = elem;
  }}
  onEnd={() => {
    this.saveSignature();
  }}
/>
```

and on `saveSignature` I just get the base64 encoded image and store it in the state. Am I doing something wrong?

**Comment by khrizt** [comment]
Looks like doing a `setState` call inside `onEnd` callback removes the signature, but if I return false on `shouldComponentUpdate` when drawing the image remains in its place.

**Comment by khrizt** [comment]
I've been able to resolve the issue by not calling saveSignature on the onEnd method but in my own button (I've tried and failed with the clearOnResize flag), but maybe there's something to look into there.

**Comment by agilgur5** [comment]
This seems more like a problem with the way you're using React, not a problem inside this component (and therefore out of scope), but you didn't post your full code (or, preferably, a fiddle) that you reference here, so it makes it difficult to help or interpret in any case.

As with any component that holds state, you will lose all the state if the component is unmounted at any point -- even if it is remounted momentarily. If the wrapping component has `shouldComponentUpdate` returning `false`, then none of its descendents in the hierarchy, including this component, will even attempt to re-render. I've often seen this problem when folks write, for instance:

```
this.state.whatever
  ? <comp ... />
  : <etc ... />
```
which means that whenever `whatever` changes, `comp` will be unmounted. Not sure if that's your case since there's no fiddle / source code to see, but that's a case I often see if that's helpful.

**Comment by miketrexler** [comment]
I encountered the same issue when trying to use the field with redux-form.

In the react-signature-pad I noticed that the canvas is cleared when it is mounted.

For redux-form I must call the input.onChange even to get its value. This causes the input to be re-rendered, which clears it the first time.

Here is how I got it to work without clearing itself. Basically I called the onChange even twice: onEnd, and when the componentDidMount:

```
class SignatureInput extends React.Component {
  handleSignatureEnd = e => {
    const dataURL = this.sigCanvas.toDataURL();
    this.props.input.onChange(dataURL);
  };
  componentDidMount() {
    const dataURL = this.sigCanvas.toDataURL();
    this.props.input.onChange(dataURL);
  }
  render() {
    return (
      <SignatureCanvas
        ref={ref => {
          this.sigCanvas = ref;
        }}
        onEnd={this.handleSignatureEnd}
        canvasProps={{ width: 500, height: 200, className: 'sigCanvas' }}
        clearOnResize={false}
      />
    );
  }
}
```
