### ISSUE TITLE
npm version issue

### ISSUE THREAD

**Issue by moimael** [agilgur5/react-signature-canvas#18]
Hi,

I installed the 0.2.3 version a few times ago with npm, but now npm is telling me the latest version available is 0.1.9. Was it removed ?

Thanks

**Comment by agilgur5** [comment]
No, it is most certainly still there: https://github.com/agilgur5/react-signature-canvas/releases . NPM says `0.1.9` is the latest because it is the "latest" chronologically.
Per https://github.com/agilgur5/react-signature-canvas/pull/14#issuecomment-354422891 , `0.1.9` is a backport of `0.2.3`.

Apparently I should have released the backport first, and then the original version (which is counterintuitive), because NPM shows "latest" meaning chronologically, instead of "latest" meaning highest version number (which is much more intuitive to users).

**Comment by agilgur5** [comment]
Can confirm with release of v0.2.4 / v0.1.10 for #16 that NPM sets "latest version" chronologically, so I released v0.1.10 first and then v0.2.4

**Comment by moimael** [comment]
Next time you can publish them in the order you want, you just have to tag the latest package using:
`npm publish --tag latest`

See here: https://docs.npmjs.com/getting-started/using-tags

**Comment by agilgur5** [comment]
Per those docs, `latest` is the _default_ tag, so unless you publish with a different tag, it'll always be tagged as `latest`. It actually doesn't specify how to not place any tag. So that doesn't solve the problem, unless one can publish just the tag itself without having a new version (i.e. publish v0.2.x then v0.1.x then the same v0.2.x but with latest) -- but that's not clear from the docs either

**Comment by agilgur5** [comment]
Per the commits that reference this issue (f430037 , 3ed2d88 , and 52ee87a ), I've resolved this by adding a `publishConfig` to the `package.json` of backported/non-latest branches (as of now, v0.3.x, v0.2.x, and v0.1.x).

This feature [isn't particularly documented well](https://docs.npmjs.com/files/package.json#publishconfig), but by adding it to `publishConfig` with a `tag` a maintainer doesn't have to remember to add a different tag each time when releasing a backported version just so it won't be tagged as latest.
