### ISSUE TITLE
resize also clears backgroundColor

### ISSUE THREAD

**Issue by davisford** [agilgur5/react-signature-canvas#26]
I get why the canvas is cleared on a resize, but if you call the `.clear()` api, it persists the `backgroundColor` whereas, if you do a resize, the `backgroundColor` is wiped out.

How to keep or restore the `backgroundColor` on a resize?

**Comment by agilgur5** [comment]
Ah, well that would be because the `_resizeCanvas` method doesn't call `.clear()` (https://github.com/agilgur5/react-signature-canvas/blob/62c371419e5b39be60e1ecde71acc185292f1d58/src/index.js#L78) . Changing the size of the canvas causes it to clear iirc.

Reading through now, I see that the `clearOnResize` prop could be a bit confusing due to this slight difference in behavior.

Hmm, I'll need to think a bit more about how to persist the color. Backgrounds don't seem to be used very often (`trim-canvas` doesn't support it either) so it's a bit of an edge case. Off the top of my head, the prop may or may not work, but a CSS background color would (not sure if you've tried either or both). There is no callback on the resize handler, so if you wanted to re-write it back to the previous color you might need to bind another handler yourself.

I think adding a `.clear()` to the end of `_resizeCanvas` should be safe / not breaking if done only when a resize occurs, which is probably the ideal fix. Another option that maybe should exist anyway is a callback for `afterResize`

**Comment by agilgur5** [comment]
@davisford I've added a call to `.clear()` at the end of `_resizeCanvas` in [v1.0.1](https://github.com/agilgur5/react-signature-canvas/releases/tag/v1.0.1) in 072e615 , so this should no longer be an issue.

Please note that while the resize feature now properly supports `backgroundColor`, the issue in https://github.com/agilgur5/react-signature-canvas/issues/22#issuecomment-420914077 still exists, so the `backgroundColor` prop is not yet supported by _all_ features, namely trimming. Due to https://github.com/agilgur5/trim-canvas/issues/4 , I'm thinking of either removing support for Canvas-based background colors (can still use CSS-based background colors) or requiring `rgba()` formatting if one is planning to use the trimming feature.

**Comment by agilgur5** [comment]
Backported into v0.3.1, v0.2.5, and v0.1.11 as https://github.com/agilgur5/react-signature-canvas/commit/186658489d83ae60bacff3fe572895fcf4c042e8 , https://github.com/agilgur5/react-signature-canvas/commit/e8e971aaadabf06809eca2381b2d6536ee3ef59e , and https://github.com/agilgur5/react-signature-canvas/commit/85da29f9121a9a4e4c43a93e54ecc2c368b743e0
