### ISSUE TITLE
clearOnResize property does not work properly

### ISSUE THREAD

**Issue by faridarzpeyma** [agilgur5/react-signature-canvas#37]
When you set clearOnResize property to false after certain breakpoints it still clears the canvas.

**Comment by agilgur5** [comment]
Sorry, I'm not sure what you're referring to by "certain breakpoints" and can't reproduce this. Like #30, you'll have to provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) or demo displaying this behavior, such as:

- a CodeSandbox example (or equivalent) or
- a screencapture of it at the demo site and the steps you took to reproduce it

Can re-open and analyze the issue once I can reproduce it.

**Comment by agilgur5** [comment]
If I'm deducing correctly, I think you meant response media breakpoints, in which case, here's a video of me using the [demo link](https://agilgur5.github.io/react-signature-canvas/), opening React DevTools, setting `clearOnResize` to `false`, and it not being cleared when I change to various breakpoints:

https://www.loom.com/share/028e661180d3494c8147e76b978eb1ea

This covers a few more breakpoints and corner resizing + manual resizing, but is otherwise very similar to the video for #30
