### ISSUE TITLE
TypeError: Cannot read property 'off' of null

### ISSUE THREAD

**Issue by Naghal** [agilgur5/react-signature-canvas#39]
![Selection_815](https://user-images.githubusercontent.com/29404633/72450293-1aa01480-3788-11ea-974a-1344a7ce0ad0.png)
Hi!
Following the installation of your package, I am getting the error "TypeError: Cannot read property 'off' of null". Here is a minimal code to reproduce:

```
import React from 'react';
import SignaturePad from 'react-signature-canvas';

const TOKEN_PARAM = 'token';
class ConsentForm extends React.Component{

    constructor(props) {
        super(props);
    }

    render() {
        return (
            <SignaturePad />
        );
    }
}
export default ConsentForm;
```
I am using Chrome and react-signature-canvas 1.0.3. Also, It does the same error if I copy the code in your codepen.

**Comment by agilgur5** [comment]
> Here is a minimal code to reproduce:

Sorry, this is not a reproduction, this code does not call the `off` function or even create a ref in order to do so. It is not minimal either, there's an unused `TOKEN_PARAM` variable, it's not rendered to DOM here, this is not standalone, etc.

> Also, It does the same error if I copy the code in your codepen.

Again, this is not a reproduction nor standalone or minimal, so this cannot just be copied, but with some modifications to make it so, this code does indeed run in the CodeSandbox:
<img width="962" alt="Screen Shot 2020-01-21 at 4 22 15 PM" src="https://user-images.githubusercontent.com/4970083/72812517-4e88a780-3c6a-11ea-9004-88ff0cefb96d.png">

Please provide an actual, minimal reproduction or a failing test case, [`off` passes its tests](https://github.com/agilgur5/react-signature-canvas/blob/d449c18b5d3b7e3bda22bdafcc7e9ddba9e51cd7/src/index.spec.js#L201-L207).
