### ISSUE TITLE
getTrimmedCanvas().toDataURL('image/svg+xml') returns data:image/png

### ISSUE THREAD

**Issue by Antonyan7** [agilgur5/react-signature-canvas#49]
Hi there, Problem is the return type of signaturePadRef.current.getTrimmedCanvas().toDataURL('image/svg+xml');
may be there are different ways to get SVG from Trimmed Canvas

**Comment by agilgur5** [comment]
So this isn't possible on a native Canvas element -- as far as I know, [no browser has support for native `'image/svg+xml'`](https://kangax.github.io/jstests/toDataUrl_mime_type_test/). This seems to be because the Canvas is [inherently a raster/bitmap format](https://github.com/gliffy/canvas2svg/issues/10#issuecomment-55754803), and so there is no straightforward conversion.

This is supported when directly using `toDataURL` on the ref because [`signature_pad` implements it under-the-hood](https://github.com/szimek/signature_pad/blob/2171e510b74362a8dd7c8e7fc77a142f16a4aed1/src/signature_pad.js#L112) by converting its tracking to SVG.

There might be an existing library to convert Canvas to SVG, but I don't of one that is up-to-date and functions like you probably want.

**Comment by Antonyan7** [comment]
Thank you, I was create new one with signature_pad

**Comment by Antonyan7** [comment]
But i Think browser support for image+xml exists😄😄
