### ISSUE TITLE
how to pre populate the data?

### ISSUE THREAD

**Issue by darshanksexathought** [agilgur5/react-signature-canvas#53]
```jsx
<SignatureCanvas 
  penColor='green'
  canvasProps={{width: 500, height: 200, className: 'sigCanvas'}}
  ref={(ref) => { this.sigPad = ref }} />
```
when this is rendered the ref variable is still the default `{}`
how can we set a value when it is rendered?

**Comment by agilgur5** [comment]
I'm not really sure why you'd want to pre-populate the data -- normally one fills out a signature from scratch.

In the example, [I use a standard `<img />` tag](https://github.com/agilgur5/react-signature-canvas/blob/d449c18b5d3b7e3bda22bdafcc7e9ddba9e51cd7/example/app.js#L37-L40) to show an existing signature.

That being said, there are [`fromData` and `fromDataURL` methods exposed in the API](https://github.com/agilgur5/react-signature-canvas#api) and that's how you'd populate it.

> when this is rendered the ref variable is still the default `{}`

React `refs` only get set after the component has been mounted. So you can only use one inside of or after `componentDidMount` has been called.

**Comment by Zwyx** [comment]
> I'm not really sure why you'd want to pre-populate the data

I believe it goes more toward the React style of doing things: declarative instead of imperative.
It also has to do with [controlled components](https://reactjs.org/docs/forms.html#controlled-components). Using ref is associated [uncontrolled components](https://reactjs.org/docs/uncontrolled-components.html).

For instance, here's a typical `input` in React:
```javascript
<input type="text" value={this.state.value} onChange={this.handleChange} />
```

For `SignatureCanvas`, it would be:
```javascript
<SignatureCanvas
  data={this.state.signature} // Type of `this.state.signature` could be `SignaturePad.Point[][]`
  onEnd={data => this.setState({signature: data})}
/>
```

What's you opinion?

Anyway, thank you for having created react-signature-canvas ;-)

**Comment by agilgur5** [comment]
@Zwyx I built one of the first production websites to use React and have been using it for almost 6 years (`react-signature-canvas` itself is 4 years old), I'm well aware of what idiomatic React looks like.

Just because React prefers or has an opinion toward some style, does not mean that it is always appropriate. Most wrapper components are not controlled and they really can't be. The Canvas element itself doesn't even work like that, it stores data internally and renders on its own.

> For `SignatureCanvas`, it would be:

Other than this being really hacky to achieve (if even achievable), it would also be quite inefficient and could cause lag. A Canvas element doesn't work like that, so this is basically asking to transform data in and out _on each stroke_. A signature pad must be low latency though.

> Using ref is associated with [uncontrolled components](https://reactjs.org/docs/uncontrolled-components.html).

Yes, this is basically an uncontrolled component and one can/should use it as such. Latency is also a common use for uncontrolled components. E.g. if you have a controlled `<textarea />` with enough text in it, you'll notice it starts to lag; Draft JS works very differently from an idiomatic controlled React component as well.

> I believe it goes more toward the React style of doing things

That doesn't really answer the question, a style is not a use-case. The only use-case I see is editing, and one isn't normally allowed to edit a signature, as I've said. One wouldn't pre-populate a consent checkbox either.

I'm also not sure OP was thinking what you were either and I would ask to not hijack existing threads. You can create a separate issue instead.

**Comment by Zwyx** [comment]
> > I believe it goes more toward the React style of doing things
> 
> That doesn't really answer the question, a style is not a use-case.

You're right, I wasn't clear here. The use-case I had in mind (my use-case) was to set the data for a read only component, as talked in https://github.com/agilgur5/react-signature-canvas/issues/54.
