### ISSUE TITLE
React 17 support in peerDeps range

### ISSUE THREAD

**Issue by mihkeleidast** [agilgur5/react-signature-canvas#58]
This module does not currently allow React 17 in it's peerDependency range. Requesting that this would be allowed.

**Comment by agilgur5** [comment]
Yea was planning on making that change soon. Should probably work fine with React 17 since it only changes event capture and `react-signature-canvas` and `signature_pad` don't rely on React's event capture.

I'll have to update the devDep and make sure tests pass first. Might get to it in the coming week as I've been looking to get back to this library and make some merges I put off.

In any case, it's just a warning, so it should not be a blocker.

**Comment by mihkeleidast** [comment]
Would you accept a PR if everything works? I like to strictly follow peerDependency ranges so this may block our upgrade soon.

**Comment by ctrlaltdylan** [comment]
Would also be open to lend a hand if needed

**Comment by JenRuey** [comment]
Hi, would like to know when the solution will be released. Knowing this will come together with other important fixes but just want to confirm the date.

**Comment by mihkeleidast** [comment]
Now that npm v7 has been released, this is becoming more of a blocker to upgrading. npm@7 throws an error if peerDeps cannot be resolved correctly.

**Comment by ashen780** [comment]
any quick workaround to make this work on react 17?

**Comment by luke9216** [comment]
@agilgur5 can we get an update on this? Cheers

**Comment by jmalbite** [comment]
Hi @luke9216 how to use your package?

**Comment by Sean-Y-X** [comment]
Any plan when React 17 support will be added?

**Comment by agilgur5** [comment]
Released in [v1.0.5](https://github.com/agilgur5/react-signature-canvas/releases/tag/v1.0.5)
