### ISSUE TITLE
How to change the position of an inserted picture?

### ISSUE THREAD

**Issue by TomatoesMan** [agilgur5/react-signature-canvas#60]
How to change the position of the inserted picture?

**Comment by agilgur5** [comment]
## background picture? Try CSS `background-image`

I'm not sure what is meant by "inserted picture"? Pictures/photos aren't meant to be used with this component. If you are trying to use a picture as a background for the signature, I might suggest using [the CSS `background-image` property](https://developer.mozilla.org/en-US/docs/Web/CSS/background-image) instead.

## `fromDataURL`? Upstream limitation

Did you mean a data URL inserted by [`fromDataURL`](https://github.com/agilgur5/react-signature-canvas#api)? If so, there is unfortunately no way to add an offset to the dataURL due to an upstream limitation in `signature_pad`. On [this line upstream](https://github.com/szimek/signature_pad/blob/2171e510b74362a8dd7c8e7fc77a142f16a4aed1/src/signature_pad.js#L105), the offsets are hard-coded to `0` unfortunately.

That being said, https://github.com/szimek/signature_pad/pull/538 added support for offsets and was recently released with v4.0.0. So once we upgrade to v4.0.0, it will be possible to add offsets to `fromDataURL`'s `options` parameter, if that's what you were looking for.

**Comment by agilgur5** [comment]
Closing as stale
