### ISSUE TITLE
Convert raw array data (`toData`) to image so it can be scaled?

### ISSUE THREAD

**Issue by alilland** [agilgur5/react-signature-canvas#75]
For the last few years i've used this component to get signatures, i've been saving the data in its raw array form instead of a PNG

on load from the server is there any way I can use this component to convert the data to a PNG? i'm having a lot of trouble trying to figure out how to get the signature to scale down from its original size

the original signature was signed with a hit-box of `160px x 650px` and , but now I need to scale it down to `160px x 288px`

```javascript
// ... what i'm doing now

componentDidMount () {
  // ...
  this.setState({ record }, () => {
    const signature = this.refs.mySignature
    if (record.signature && record.signature.length > 0) 
      signature.fromData(record.signature)
      signature.off()
    }
  })
}

render () {
  return (
    <SignatureCanvas
       ref={'mySignature'}
       penColor={'var(--default-font-color)'}
       canvasProps={{
         width: 650,
         height: 160,
        className: 'mySignature'
      }}
    />
  )
}
```

**Comment by alilland** [comment]
it was definitely hacky on the UI component side, but on the loading side this is what i ended up doing

```javascript
this.setState({ record }, () => {
    const signature = this.refs.mySignature
    let url = null
    if (record.signature && record.signature.length > 0) {
      signature.fromData(record.signature)
      url = signature.toDataURL()
      signature.off()
    }
    this.setState({ dataURL: url, hideSignature: url === null })
  })
```

```javascript
<div style={{ marginBottom: 24 }}>
  <small>Customer Signature</small>
  {!dataURL &&
     <div>
       {!hideSignature &&
         <SignatureCanvas
           ref={'mySignature'}
           penColor={'var(--default-font-color)'}
           canvasProps={{
             width: 650,
             height: 160,
             className: 'mySignature'
           }}
         />
       }
    </div>
  }
  {dataURL &&
    <div>
      <img src={dataURL} style={{ height: '0.5in' }} />
    </div>
  }
</div>
```

basically i had to control the following things:
- on page load the signature component cannot be hidden or refs will break
- on load the componentDidMount function catches the canvas and sees the canvas with the same hitbox as the original signature
- after state has been updated a data url can be generated from the ref and re-applied to state
- lastly i had to figure out a way to hide the original canvas if no signature was present, so it just got wrapped in a stateful boolean...

I sort of wish the component didnt use refs, and i suspect they would break big time with the new react hooks refs, but oh well ... got it working 🤷🏻‍♂️

**Comment by agilgur5** [comment]
> is there any way I can use this component to convert the data to a PNG?

This is really more an upstream question as it's not really specific to the component but to `signature_pad` itself, which this component merely wraps and adds some basic helpers to.

`SignaturePad#fromData` has no way of scaling, but there is a way to scale with `canvas` generically data URLs. For instance, newer versions of `fromDataURL` [support scaling](https://github.com/szimek/signature_pad/blob/28dbb4ccabcd045bdf4355b965ad9d0f60dff09a/src/signature_pad.ts#L128) via `canvas` context's [`drawImage` function](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage), which has support for re-sizing.

Once you instantiate the original canvas with `fromData`, you can use `toDataURL` to get a data URL back instead. Then you can either resize the original canvas and insert with `fromDataURL`, or use a second, hidden, canvas to resize it (or vice-versa with which is hidden).
This is a client-side only solution using only the existing libraries, so it's non-trivial to implement, but there are other routes you could use to convert the raw data more directly to an image (though as far as I know, no existing libraries on that front, so may have to implement your own algorithm for that).

> the original signature was signed with a hit-box of `160px x 650px` and , but now I need to scale it down to `160px x 288px`

That being said, this is not an even ratio, so you will get distortion of signatures when resizing this.

<hr>

Closing as this issue is really more suited for upstream `signature_pad` and is not specific to this component.

**Comment by agilgur5** [comment]
> and i suspect they would break big time with the new react hooks refs

Your suspicion is invalid given that there are multiple examples in the issues of using complicated hooks and refs with this component.
`useRef` is also merely a wrapper API around the various existing refs APIs and the React team did not change how refs work in releasing hooks -- it is fully backward-compatible, after all.

> I sort of wish the component didnt use refs

This is a proper use-case for refs, wrapping an existing JS "widget" and exposing its APIs in a way that is more idiomatic for React. All the props and callbacks that are provided in this component make it more idiomatic React, but there is no real way to _completely_ workaround the fact that  `signature_pad`'s APIs are _imperative_ and so are the `canvas` element's APIs itself, along with both storing data internally.
This is also described detail in https://github.com/agilgur5/react-signature-canvas/issues/53#issuecomment-667690351 where I explain how this is very much meant to be an "uncontrolled" component and aligns _very well_ with the use-cases for an uncontrolled component.

If you have worked out the structure of how to achieve this wrapping differently (without performance implications as mentioned in the above linked comment), you're welcome to provide _constructive_ ideas in separate issues, but I would highly recommend against making broad, invalid, and passive-aggressive remarks in any comment on any open-source repo. Especially so if you have not given your claims significant due diligence and investigation. Most maintainers have spent 100s of hours on their libraries and know their use-cases very well, so I would suggest being more respectful of both their time and expertise, especially when asking for assistance.

**Comment by alilland** [comment]
Appreciate the constructive criticism, no offense was meant, I can see how it would be misconstrued --

for end users it would be beneficial to include more usage examples, hopefully in the near future I might be able to make some pull requests for documentation updates 👍

I appreciate the library very much and I know how it can be dumping hours and hours into projects then to have someone make uneducated comments, if this library is able to support those features the best thing that can be done is to buildout the sample usage folder with as many use cases as possible
