### ISSUE TITLE
`TypeError: sigCanvas.current.getTrimmedCanvas is not a function`

### ISSUE THREAD

**Issue by pneha2296** [agilgur5/react-signature-canvas#92]
```js
const sigCanvas = useRef({});
const onClickSignatureUpload = (url, id) => {
    console.log("signature Upload start");
    fetch(url)
      .then(res => res.blob())
      .then(blob => {
        const file = new File([blob], "signature.png", { type: "image/png" });
        const body = {
          fileName: file?.name,
          mimeType: file?.type,
          directory: "document",
        };
        dispatch(createSignedUrl(body))
          .then((response) => {
            setValue(id, response?.s3Key);
            dispatch(uploadFile(response?.signedUrl, file));
          })
          .catch((error) => {
            console.log(error);
          })
          .finally(() => {
            const fileType = {
              title: file?.name,
              type: file?.type,
              size: file?.size,
              percentage: 100,
            };
            uploadedFiles.push(fileType);
            setFileUploadDeatisl(uploadedFiles);
          });
      })
  }
```
  
![image](https://user-images.githubusercontent.com/63401708/190955550-3bce0b16-497d-4ae9-a65e-6cfad363c792.png)

# #91 

Here I attach reference things that are missing in issue no #91 
please resolve before close

**Comment by pneha2296** [comment]
Here I attach reference things that are missing in issue no #91 
please resolve before close

**Comment by agilgur5** [comment]
Please don't make duplicate issues for no reason. You can leave comments on closed issues.

If you create another duplicate, you will be blocked for spamming.

> please resolve before close

Please be respectful to maintainers who are volunteering their free time to help you. I am not paid to do this.
If you are not respectful, spamming, or otherwise abusive, you will be blocked.

Issues are also _not_ a support forum, they are for reporting bugs, suggesting features, etc. StackOverflow is a support forum and you are welcome to use that for help with coding issues.

Please read [my response](https://github.com/agilgur5/react-signature-canvas/issues/91#issuecomment-1250154937) _in full_. That includes clicking and reading all links _in full_ as well.
If you are not willing to spend your time doing that, then please do not ask others to spend time figuring out your issues -- that is not respectful of their time.

You did not provide what I asked for. I gave 3 options and this is not one of them. This is also, _again_, not a _minimal_ repro, not a full component, has various unrelated pieces, and is not reproducible.
I once again had to fix the formatting here too...

As I said in in #91, this seems to be an issue with your usage of React, and _not_ a `react-signature-canvas` issue. You did not provide any evidence here to suggest otherwise.

**Comment by pneha2296** [comment]
> 

I face issue and I raised you don't event listen and asking me like this that you will going to blocked me you don't want to solve tell me simple that you are not providing support before this I raised issue and they solved that's why I am doing. 

and reason behind recreating issue is just that I didn't get solution of problem.
I am sorry to be wasting your time.
